title: Ruairi O'Donohoe
description: Data Analyst, ETL Engineer, Machine Learning / Deep Learning Engineer
github_username: ruairiodonohoe
remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme
