title: Ruairí O'Donohoe
description: Data Analyst | ETL Engineer | ML & Deep Learning Engineer
github_username: ruairiodonohoe

# Set the theme
theme: jekyll-theme-cayman

# Sass settings
sass:
  style: compressed
